// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoLabKarts.Data;

#nullable disable

namespace ProjetoLabKarts.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524115645_f3")]
    partial class f3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoLabKarts.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RowsPerPage")
                        .HasColumnType("int");

                    b.Property<string>("SelectedColumns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedGraphs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedProgressBar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ViewName")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("ProjetoLabKarts.Models.SessaoKart", b =>
                {
                    b.Property<string>("NomeFicheiro")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CoordenadaLat")
                        .HasColumnType("float");

                    b.Property<double>("CoordenadaLong")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInsercao")
                        .HasColumnType("datetime2");

                    b.Property<string>("MelhorVolta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePiloto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroMelhorVolta")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVoltas")
                        .HasColumnType("int");

                    b.Property<double>("VelocidadeMax")
                        .HasColumnType("float");

                    b.HasKey("NomeFicheiro");

                    b.ToTable("SessoesKart");
                });
#pragma warning restore 612, 618
        }
    }
}
